### ISSUE TITLE
Extract packer archive task fails when `ansible` is running from remote

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-packer-binary#3]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
unreleased
```

##### CONFIGURATION

```ini
[defaults]
roles_path = roles.galaxy:roles

[ssh_connection]
pipelining = True
```

##### OS / ENVIRONMENT

ansible 2.3.2.0 (v2.3.2.0-1 c7052b42c7) on FreeBSD 10.1

##### SUMMARY

Extract packer archive task fails when `ansible` is running from remote.

##### STEPS TO REPRODUCE

```yaml
- hosts: jenkins-slave
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  roles:
    - role: reallyenglish.packer-binary
```

```
TASK [reallyenglish.packer-binary : Extract packer archive] ********************
fatal: [192.168.33.12]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/var/cache/packer-binary/packer_1.0.4_freebsd_amd64.zip' in expected paths."}
```

##### EXPECTED RESULTS

the zip file is extracted.

##### ACTUAL RESULTS

the task failed.
